const List<String> exercisesList = [
  'Push-ups',
  'Squats',
  'Lunges',
  'Plank',
  'Burpees',
  'Mountain Climbers',
  'Jumping Jacks',
  'Sit-ups',
  'Crunches',
  'Leg Raises',
  'Bicep Curls',
  'Tricep Dips',
  'Shoulder Press',
  'Deadlifts',
  'Bench Press',
  'Pull-ups',
  'Chin-ups',
  'Dumbbell Rows',
  'Kettlebell Swings',
  'Box Jumps',
];
